// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTQQIY51l90ydvMHispejNdkZWrRpjpo',
    appId: '1:51339030477:web:9dcc91f90864355d72de84',
    messagingSenderId: '51339030477',
    projectId: 'lasertuner-59b92',
    authDomain: 'lasertuner-59b92.firebaseapp.com',
    storageBucket: 'lasertuner-59b92.firebasestorage.app',
    measurementId: 'G-P1Y5Y0JC4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBshLk9QV9WY9TPUlYwt43h2P_pnhYnuVU',
    appId: '1:51339030477:android:a0338da0ad33c2a172de84',
    messagingSenderId: '51339030477',
    projectId: 'lasertuner-59b92',
    storageBucket: 'lasertuner-59b92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDVO8N81q7BHpiZBLnWGXGyfn2XS6QS1w',
    appId: '1:51339030477:ios:946c3bb7f02687c072de84',
    messagingSenderId: '51339030477',
    projectId: 'lasertuner-59b92',
    storageBucket: 'lasertuner-59b92.firebasestorage.app',
    iosBundleId: 'com.example.lasertuner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDVO8N81q7BHpiZBLnWGXGyfn2XS6QS1w',
    appId: '1:51339030477:ios:946c3bb7f02687c072de84',
    messagingSenderId: '51339030477',
    projectId: 'lasertuner-59b92',
    storageBucket: 'lasertuner-59b92.firebasestorage.app',
    iosBundleId: 'com.example.lasertuner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChTQQIY51l90ydvMHispejNdkZWrRpjpo',
    appId: '1:51339030477:web:5d74b86e78dce64272de84',
    messagingSenderId: '51339030477',
    projectId: 'lasertuner-59b92',
    authDomain: 'lasertuner-59b92.firebaseapp.com',
    storageBucket: 'lasertuner-59b92.firebasestorage.app',
    measurementId: 'G-1LM04DCCJX',
  );
}
